// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2x1REQqs9dNFbsYhzONnzHnPo8vE4ZVQ',
    appId: '1:971849209350:web:673c7bc040adbd45499587',
    messagingSenderId: '971849209350',
    projectId: 'balanced-meal-27bdc',
    authDomain: 'balanced-meal-27bdc.firebaseapp.com',
    storageBucket: 'balanced-meal-27bdc.firebasestorage.app',
    measurementId: 'G-95EM8NNZSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOIL05PvAm4xGemVOF6jzo1UPoCJPvi80',
    appId: '1:971849209350:android:85cb6d39a73e5fcd499587',
    messagingSenderId: '971849209350',
    projectId: 'balanced-meal-27bdc',
    storageBucket: 'balanced-meal-27bdc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDms5vMAFQ-u7QWc5q_FRqC9LJGiCW44Hg',
    appId: '1:971849209350:ios:160a5775d9e34a0d499587',
    messagingSenderId: '971849209350',
    projectId: 'balanced-meal-27bdc',
    storageBucket: 'balanced-meal-27bdc.firebasestorage.app',
    iosBundleId: 'com.balance.balancedMeal',
  );

}